import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Download, ExternalLink, FileText, Search, Trash2, Upload, X } from 'lucide-react'
import { api, FILE_BASE_URL, uploadNote } from '../services/api'
import { subjects } from '../data/subjects'

const fileSize = (bytes = 0) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`
const date = value => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value))

export default function Notes() {
  const { subject: subjectParam } = useParams()
  const selectedSubject = subjectParam ? decodeURIComponent(subjectParam) : ''
  const [notes, setNotes] = useState([]), [canManage, setCanManage] = useState(false), [query, setQuery] = useState(''), [filter, setFilter] = useState(selectedSubject), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState(''), [uploadOpen, setUploadOpen] = useState(false), [uploading, setUploading] = useState(false), [progress, setProgress] = useState(0), [viewer, setViewer] = useState('')
  const [form, setForm] = useState({ title: '', subject: selectedSubject || subjects[0], description: '', file: null })
  const load = async () => { setLoading(true); setError(''); try { const data = await api('/notes'); setNotes(data.notes); setCanManage(data.canManage) } catch (err) { setError(err.message || 'Unable to load notes.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  useEffect(() => { setFilter(selectedSubject); setForm(current => ({ ...current, subject: selectedSubject || current.subject })) }, [selectedSubject])
  const activeFilter = selectedSubject || filter
  const shown = useMemo(() => notes.filter(note => (!activeFilter || note.subject === activeFilter) && `${note.title} ${note.description || ''} ${note.subject}`.toLowerCase().includes(query.toLowerCase())), [notes, activeFilter, query])
  const upload = async event => { event.preventDefault(); setError(''); setNotice(''); if (!form.title.trim()) return setError('PDF title is required.'); if (!form.file) return setError('Select a PDF to upload.'); if (!form.file.name.toLowerCase().endsWith('.pdf') || form.file.type !== 'application/pdf') return setError('Only PDF files are allowed.'); if (form.file.size > 10 * 1024 * 1024) return setError('PDF files must be 10 MB or smaller.'); setUploading(true); setProgress(0); try { const body = new FormData(); body.append('title', form.title); body.append('subject', selectedSubject); body.append('description', form.description); body.append('file', form.file); await uploadNote(body, setProgress); setNotice('PDF uploaded successfully.'); setUploadOpen(false); setForm({ title: '', subject: selectedSubject, description: '', file: null }); await load() } catch (err) { setError(err.message) } finally { setUploading(false) } }
  const remove = async note => { if (!window.confirm(`Delete “${note.title}”? This cannot be undone.`)) return; setError(''); try { await api(`/notes/${note._id}`, { method: 'DELETE' }); setNotes(items => items.filter(item => item._id !== note._id)); setNotice('PDF deleted.') } catch (err) { setError(err.message) } }
  const open = note => `${FILE_BASE_URL}${note.fileUrl}`
  return <>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-lime-300">STUDENT NOTES</p><h1 className="mt-2 text-3xl font-semibold">{selectedSubject ? `${selectedSubject.split(' — ')[0]} Notes` : 'Notes library'}</h1><p className="mt-2 text-slate-400">Browse subject PDFs shared by authorized note administrators.</p></div>{selectedSubject && canManage && <button className="btn-primary gap-2" onClick={() => setUploadOpen(true)}><Upload size={17}/> + Upload PDF</button>}</div>
    <section className="mt-8 rounded-2xl border border-white/10 bg-panel p-4"><div className="relative"><Search className="absolute left-3 top-3 text-slate-500" size={18}/><input className="w-full rounded-xl border border-white/10 bg-white/5 py-3 pl-10 pr-4 text-sm outline-none placeholder:text-slate-500 focus:border-lime-300" placeholder="Search notes by title, description or subject..." value={query} onChange={event => setQuery(event.target.value)}/></div>{!selectedSubject && <div className="mt-3 flex gap-2 overflow-x-auto pb-1"><button onClick={() => setFilter('')} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-sm ${!filter ? 'bg-lime-300 font-semibold text-slate-900' : 'border border-white/10 text-slate-300'}`}>All</button>{subjects.map(subject => <button key={subject} onClick={() => setFilter(subject)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-sm ${filter === subject ? 'bg-lime-300 font-semibold text-slate-900' : 'border border-white/10 text-slate-300'}`}>{subject.split(' — ')[0]}</button>)}</div>}</section>
    {!selectedSubject && <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{subjects.map(subject => <Link key={subject} to={`/notes/${encodeURIComponent(subject)}`} className="dash-card transition hover:border-lime-300/50"><FileText className="text-lime-300"/><h2 className="mt-4 font-semibold text-white">{subject}</h2><p className="mt-1 text-sm text-slate-400">{notes.filter(note => note.subject === subject).length} PDFs available</p></Link>)}</section>}
    {error && <p className="mt-5 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-200">{error}</p>}{notice && <p className="mt-5 rounded-xl bg-lime-300/10 p-3 text-sm text-lime-200">{notice}</p>}
    <section className="mt-8"><h2 className="font-semibold">{activeFilter ? `${activeFilter} PDFs` : 'All PDFs'}</h2>{loading ? <p className="mt-4 text-sm text-slate-400">Loading notes…</p> : shown.length ? <div className="mt-4 space-y-3">{shown.map(note => <article key={note._id} className="dash-card flex flex-col gap-4 sm:flex-row sm:items-center"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-rose-400/10 text-rose-300"><FileText size={21}/></div><div className="min-w-0 flex-1"><h3 className="truncate font-semibold text-white">{note.title}</h3><p className="mt-1 truncate text-sm text-slate-400">{note.subject} · Uploaded {date(note.createdAt)} · {fileSize(note.fileSize)}</p>{note.description && <p className="mt-1 truncate text-sm text-slate-500">{note.description}</p>}</div><div className="flex flex-wrap gap-2"><button onClick={() => setViewer(open(note))} className="rounded-lg border border-white/15 px-3 py-2 text-sm font-medium hover:border-lime-300 hover:text-lime-300"><ExternalLink className="mr-1 inline" size={15}/>View</button><a href={open(note)} download={note.originalName || note.title} className="rounded-lg border border-white/15 px-3 py-2 text-sm font-medium hover:border-lime-300 hover:text-lime-300"><Download className="mr-1 inline" size={15}/>Download</a>{canManage && <button onClick={() => remove(note)} className="rounded-lg border border-rose-300/30 px-3 py-2 text-sm font-medium text-rose-300 hover:bg-rose-300/10"><Trash2 className="mr-1 inline" size={15}/>Delete</button>}</div></article>)}</div> : <div className="mt-4 dash-card py-10 text-center"><FileText className="mx-auto text-slate-500"/><p className="mt-4 font-medium text-slate-200">{canManage ? 'No notes uploaded yet' : 'No notes available for this subject yet.'}</p><p className="mt-1 text-sm text-slate-400">Notes for {activeFilter || 'this library'} will appear here once they are uploaded.</p>{selectedSubject && canManage && <button className="mt-5 text-sm font-semibold text-lime-300" onClick={() => setUploadOpen(true)}>+ Upload PDF</button>}</div>}</section>
    {uploadOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={upload} className="w-full max-w-lg rounded-2xl bg-white p-6 text-slate-900"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Upload {selectedSubject.split(' — ')[0]} Notes</h2><p className="mt-1 text-sm text-slate-500">{selectedSubject} · PDF only · Maximum 10 MB</p></div><button type="button" disabled={uploading} onClick={() => setUploadOpen(false)} aria-label="Close upload"><X/></button></div><div className="mt-5 space-y-4"><label className="block text-sm font-medium">PDF title<input required disabled={uploading} className="field" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })}/></label><label className="block text-sm font-medium">Description <span className="font-normal text-slate-500">(optional)</span><textarea disabled={uploading} className="field min-h-24" maxLength="500" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })}/></label><label className="block text-sm font-medium">Choose PDF<input required disabled={uploading} accept="application/pdf,.pdf" type="file" className="mt-2 block w-full text-sm" onChange={event => setForm({ ...form, file: event.target.files?.[0] || null })}/></label>{form.file && <div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><FileText className="shrink-0 text-rose-500" size={20}/><div className="min-w-0"><p className="truncate text-sm font-semibold">{form.file.name}</p><p className="text-xs text-slate-500">PDF · {fileSize(form.file.size)}</p></div></div>}{uploading && <div><div className="flex justify-between text-xs text-slate-500"><span>Uploading…</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-lime-500 transition-all" style={{ width: `${progress}%` }}/></div></div>}</div><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={uploading} onClick={() => setUploadOpen(false)} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600">Cancel</button><button disabled={uploading} className="btn-primary">{uploading ? 'Uploading…' : 'Upload PDF'}</button></div></form></div>}
    {viewer && <div className="fixed inset-0 z-50 bg-black/80 p-3 md:p-8"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white"><div className="flex items-center justify-between border-b p-3"><p className="font-semibold text-slate-800">PDF viewer</p><div className="flex gap-3"><a className="text-sm font-medium text-slate-600 underline" href={viewer} target="_blank" rel="noreferrer">Open in tab</a><button onClick={() => setViewer('')} className="rounded-lg p-1 text-slate-700" aria-label="Close viewer"><X/></button></div></div><iframe title="PDF viewer" src={viewer} className="min-h-0 flex-1"/></div></div>}
  </>
}
